#include "update_journal.h"
#include <stddef.h>
#include <string.h>
static uint32_t crc32(const uint8_t *p,size_t n){uint32_t c=UINT32_MAX;while(n--){c^=*p++;for(unsigned b=0;b<8;b++)c=(c>>1)^(UINT32_C(0xedb88320)&(0U-(c&1U)));}return ~c;}
static void seal(update_journal_record_t *r){r->crc32=crc32((const uint8_t*)r,offsetof(update_journal_record_t,crc32));}
static bool has_manifest_id(const uint8_t manifest_id[16]){uint8_t combined=0U;for(size_t index=0;index<16U;++index)combined|=manifest_id[index];return combined!=0U;}
void update_journal_init(update_journal_record_t *r){if(r==NULL)return;*r=(update_journal_record_t){.magic=UPDATE_JOURNAL_MAGIC,.version=UPDATE_JOURNAL_VERSION,.state=UPDATE_JOURNAL_IDLE};seal(r);}
bool update_journal_prepare(update_journal_record_t *r,const update_manifest_t *m){if(!update_journal_is_valid(r)||m==NULL||r->state!=UPDATE_JOURNAL_IDLE||r->generation!=0U||m->app_version==0U)return false;memcpy(r->manifest_id,m->manifest_id,sizeof(r->manifest_id));r->app_version=m->app_version;seal(r);return true;}
bool update_journal_is_valid(const update_journal_record_t *r){return r!=NULL&&r->magic==UPDATE_JOURNAL_MAGIC&&r->version==UPDATE_JOURNAL_VERSION&&r->state<=UPDATE_JOURNAL_ACCEPTED&&r->crc32==crc32((const uint8_t*)r,offsetof(update_journal_record_t,crc32))&&(r->state==UPDATE_JOURNAL_IDLE||(r->app_version!=0U&&has_manifest_id(r->manifest_id)));}
bool update_journal_transition(update_journal_record_t *r,update_journal_state_t n){if(!update_journal_is_valid(r))return false; const bool ok=(r->state==UPDATE_JOURNAL_IDLE&&n==UPDATE_JOURNAL_P4_STAGED)||(r->state==UPDATE_JOURNAL_P4_STAGED&&(n==UPDATE_JOURNAL_P4_PENDING||n==UPDATE_JOURNAL_IDLE))||(r->state==UPDATE_JOURNAL_P4_PENDING&&n==UPDATE_JOURNAL_ACCEPTED)||(r->state==UPDATE_JOURNAL_ACCEPTED&&n==UPDATE_JOURNAL_IDLE); if(!ok)return false;r->state=n;seal(r);return true;}
bool update_journal_next(const update_journal_record_t *previous,update_journal_state_t next,update_journal_record_t *out){if(!update_journal_is_valid(previous)||out==NULL)return false;update_journal_record_t check=*previous;if(!update_journal_transition(&check,next))return false;*out=check;out->generation=0U;seal(out);return true;}
bool update_journal_can_follow(const update_journal_record_t *previous,const update_journal_record_t *candidate){if(!update_journal_is_valid(previous)||!update_journal_is_valid(candidate)||candidate->generation!=0U)return false;if(previous->state==UPDATE_JOURNAL_IDLE)return candidate->state==UPDATE_JOURNAL_P4_STAGED; if(memcmp(previous->manifest_id,candidate->manifest_id,sizeof(previous->manifest_id))!=0||previous->app_version!=candidate->app_version)return false;update_journal_record_t check=*previous;return update_journal_transition(&check,(update_journal_state_t)candidate->state);}
bool update_journal_set_generation(update_journal_record_t *r,uint32_t generation){if(!update_journal_is_valid(r)||generation<=r->generation)return false;r->generation=generation;seal(r);return true;}
bool update_journal_to_replay_record(const update_journal_record_t *j,update_replay_record_t *o){if(j==NULL||o==NULL||!update_journal_is_valid(j)||(j->state!=UPDATE_JOURNAL_ACCEPTED&&!(j->state==UPDATE_JOURNAL_IDLE&&j->app_version!=0U&&has_manifest_id(j->manifest_id)))||j->app_version==0U)return false;*o=(update_replay_record_t){.valid=true,.highest_app_version=j->app_version};memcpy(o->manifest_id,j->manifest_id,sizeof(o->manifest_id));return true;}
