"""Render the selected static Meteocons into LVGL 9 image descriptors.

The complete upstream package lives in design/clima/static. This generator
embeds only the 26 icons used by the Climate screen at 32x32 and 48x48 px.
It requires Chrome or Edge, Pillow, and websocket-client on the host.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import tempfile
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SVG_ROOT = ROOT / "design" / "clima" / "static" / "fill"
OUTPUT = ROOT / "firmware" / "main" / "ui" / "assets" / "np_weather_static_icons.c"
PREVIEW = ROOT / "firmware" / "build" / "weather-static-icons-preview.png"
SIZES = (32, 48)

CONDITIONS = {
    "clear": ("clear-day", "clear-night"),
    "partly_cloudy": ("partly-cloudy-day", "partly-cloudy-night"),
    "fog": ("fog-day", "fog-night"),
    "drizzle": ("partly-cloudy-day-drizzle", "partly-cloudy-night-drizzle"),
    "rain": ("partly-cloudy-day-rain", "partly-cloudy-night-rain"),
    "snow": ("partly-cloudy-day-snow", "partly-cloudy-night-snow"),
    "rain_showers": ("overcast-day-rain", "overcast-night-rain"),
    "snow_showers": ("overcast-day-snow", "overcast-night-snow"),
    "thunderstorm": ("thunderstorms-day-rain", "thunderstorms-night-rain"),
    "variable": ("overcast-day", "overcast-night"),
}
INFO = (
    ("sunrise", "clear-day"),
    ("sunset", "clear-night"),
    ("wind", "wind"),
    ("humidity", "humidity"),
    ("uv_index", "clear-day"),
    ("rain", "rain"),
)
ICONS = tuple(dict.fromkeys((*[name for pair in CONDITIONS.values() for name in pair],
                             *[asset for _, asset in INFO], "not-available")))


def c_identifier(value: str) -> str:
    return value.replace("-", "_")


def render_assets() -> dict[str, dict[int, bytes]]:
    node = shutil.which("node")
    if node is None:
        raise RuntimeError("Node.js is required to render static Meteocons assets")
    renderer_modules = Path(tempfile.gettempdir()) / "np2-meteocons-renderer" / "node_modules"
    if not (renderer_modules / "@resvg" / "resvg-js").exists():
        raise RuntimeError(
            "Install @resvg/resvg-js@2.6.2 under %TEMP%/np2-meteocons-renderer "
            "before rendering (see design/clima/README.md)"
        )
    with tempfile.TemporaryDirectory(prefix="np2_meteocons_png_") as temp_dir:
        temp_path = Path(temp_dir)
        specs = []
        for icon in ICONS:
            source = SVG_ROOT / f"{icon}.svg"
            if not source.is_file():
                raise FileNotFoundError(f"Required Meteocons SVG is missing: {source}")
            for size in SIZES:
                color = "#f4f8ff"
                if icon == "wind":
                    color = "#168dff"
                elif icon in ("sunrise", "sunset"):
                    color = "#9fc0e8"
                specs.append({"icon": icon, "source": str(source), "size": size,
                              "color": color,
                              "output": str(temp_path / f"{icon}-{size}.png")})
        spec_path = temp_path / "render-spec.json"
        spec_path.write_text(json.dumps(specs), encoding="utf-8")
        renderer = r"""
const fs = require('fs');
const { Resvg } = require('@resvg/resvg-js');
const specs = JSON.parse(fs.readFileSync(process.argv[1], 'utf8'));
for (const spec of specs) {
  const svg = fs.readFileSync(spec.source, 'utf8')
    .replaceAll('currentColor', spec.color)
    .replaceAll('#202939', spec.color);
  const png = new Resvg(svg, { fitTo: { mode: 'width', value: spec.size } })
    .render().asPng();
  fs.writeFileSync(spec.output, png);
}
"""
        environment = os.environ.copy()
        environment["NODE_PATH"] = str(renderer_modules)
        subprocess.run([node, "-e", renderer, str(spec_path)], check=True, env=environment)
        assets: dict[str, dict[int, bytes]] = {}
        for spec in specs:
            with Image.open(spec["output"]) as image:
                size = spec["size"]
                if image.size != (size, size):
                    raise RuntimeError(
                        f"Unexpected render size for {spec['icon']}: {image.size}")
                pixels = image.convert("RGBA").tobytes("raw", "BGRA")
                assets.setdefault(spec["icon"], {})[size] = pixels
        return assets


def generate() -> tuple[str, dict[str, dict[int, bytes]]]:
    assets = render_assets()

    lines = [
        '/* Generated by tools/build_meteocons_static.py; do not edit by hand. */',
        '#include "np_weather_static_icons.h"',
        '#include <stddef.h>',
        '#include <stdint.h>',
        '',
    ]
    for icon, sized_assets in assets.items():
        ident = c_identifier(icon)
        for size, pixels in sized_assets.items():
            name = f"s_{ident}_{size}"
            lines.append(f"static const uint8_t {name}_pixels[] = {{")
            for offset in range(0, len(pixels), 16):
                row = ", ".join(f"0x{byte:02x}" for byte in pixels[offset:offset + 16])
                lines.append(f"    {row},")
            lines.append("};")
            lines.append(f"static const lv_image_dsc_t {name} = {{")
            lines.append("    .header = {")
            lines.append("        .magic = LV_IMAGE_HEADER_MAGIC,")
            lines.append("        .cf = LV_COLOR_FORMAT_ARGB8888,")
            lines.append(f"        .w = {size}, .h = {size}, .stride = {size * 4}U,")
            lines.append("    },")
            lines.append(f"    .data_size = sizeof({name}_pixels), .data = {name}_pixels,")
            lines.append("};")
    lines.extend([
        "",
        "static const lv_image_dsc_t *image_by_size(const lv_image_dsc_t *small,",
        "                                                const lv_image_dsc_t *large,",
        "                                                uint8_t size)",
        "{",
        "    return size >= NP_WEATHER_STATIC_ICON_LARGE ? large : small;",
        "}",
        "",
        "const lv_image_dsc_t *np_weather_static_condition_icon(",
        "    weather_condition_t condition, bool is_day, uint8_t size)",
        "{",
        "    const bool night = !is_day;",
        "    switch (condition) {",
    ])
    enum_names = {
        "clear": "CLEAR",
        "partly_cloudy": "PARTLY_CLOUDY",
        "fog": "FOG",
        "drizzle": "DRIZZLE",
        "rain": "RAIN",
        "snow": "SNOW",
        "rain_showers": "RAIN_SHOWERS",
        "snow_showers": "SNOW_SHOWERS",
        "thunderstorm": "THUNDERSTORM",
        "variable": "VARIABLE",
    }
    for condition in CONDITIONS:
        day_icon, night_icon = CONDITIONS[condition]
        lines.extend([
            f"    case WEATHER_CONDITION_{enum_names[condition]}:",
            f"        return night ? image_by_size(&s_{c_identifier(night_icon)}_32,",
            f"                                      &s_{c_identifier(night_icon)}_48, size)",
            f"                     : image_by_size(&s_{c_identifier(day_icon)}_32,",
            f"                                      &s_{c_identifier(day_icon)}_48, size);",
        ])
    lines.extend([
        "    default:",
        "        return image_by_size(&s_overcast_day_32, &s_overcast_day_48, size);",
        "    }",
        "}",
        "",
        "const lv_image_dsc_t *np_weather_static_info_icon(",
        "    np_weather_static_info_icon_t icon, uint8_t size)",
        "{",
        "    switch (icon) {",
    ])
    for enum_name, asset in INFO:
        lines.extend([
            f"    case NP_WEATHER_STATIC_{enum_name.upper()}:",
            f"        return image_by_size(&s_{c_identifier(asset)}_32,",
            f"                              &s_{c_identifier(asset)}_48, size);",
        ])
    lines.extend([
        "    default:",
        "        return image_by_size(&s_not_available_32, &s_not_available_48, size);",
        "    }",
        "}",
        "",
    ])
    return "\n".join(lines), assets


def write_preview(assets: dict[str, dict[int, bytes]]) -> None:
    cell = 96
    columns = 6
    rows = (len(ICONS) + columns - 1) // columns
    sheet = Image.new("RGBA", (columns * cell, rows * cell), (8, 18, 28, 255))
    from PIL import ImageDraw
    draw = ImageDraw.Draw(sheet)
    for index, icon in enumerate(ICONS):
        x, y = (index % columns) * cell, (index // columns) * cell
        pixels = Image.frombytes("RGBA", (48, 48), assets[icon][48], "raw", "BGRA")
        sheet.alpha_composite(pixels, (x + 24, y + 5))
        draw.text((x + 3, y + 58), icon[:16], fill=(220, 232, 245, 255))
    PREVIEW.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(PREVIEW)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--preview", action="store_true", help="also write a contact sheet under firmware/build")
    args = parser.parse_args()
    source, assets = generate()
    OUTPUT.write_text(source, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT} ({OUTPUT.stat().st_size:,} bytes)")
    if args.preview:
        write_preview(assets)
        print(f"Wrote {PREVIEW}")


if __name__ == "__main__":
    main()
