"""Generate immutable lookup/search metadata; never change persisted TZ order.

Country sources in tools/data are IANA tzdata 2026b public-domain tables.
They supply names only, never replace the existing POSIX rules.
"""
import csv
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / 'tools/data'
CSV = ROOT / 'firmware/main/timezone_catalog.csv'
OUTPUT = ROOT / 'firmware/main/timezone_catalog_index.inc'
primary = ['America/Sao_Paulo', 'America/Sao_Paulo',
           'America/Argentina/Buenos_Aires', 'America/New_York', 'Europe/London']
countries = {}
for line in (DATA / 'timezone-zone.tab').read_text(encoding='utf-8').splitlines():
    if line and not line.startswith('#'):
        fields = line.split('\t')
        countries[fields[2]] = fields[0]
links = {}
for line in (DATA / 'timezone-links.txt').read_text(encoding='utf-8').splitlines():
    if line.startswith('L '):
        _, target, alias = line.split()
        links[alias] = target
names = {}
for line in (DATA / 'timezone-iso3166.tab').read_text(encoding='utf-8').splitlines():
    if line and not line.startswith('#'):
        code, name = line.split('\t', 1)
        names[code] = name.replace('\u2019', "'")
# Portuguese labels for common choices; other ISO names stay authoritative.
names.update(BR='Brasil', US='Estados Unidos', GB='Reino Unido', DE='Alemanha',
             FR='França', ES='Espanha', PT='Portugal', IT='Itália', CA='Canadá',
             JP='Japão', CN='China', AU='Austrália', IN='Índia', RU='Rússia',
             MX='México', PE='Peru', CL='Chile', UY='Uruguai', AR='Argentina',
             ZA='África do Sul', NZ='Nova Zelândia')

def country(zone):
    visited = set()
    while zone not in countries and zone in links and zone not in visited:
        visited.add(zone)
        zone = links[zone]
    return names.get(countries.get(zone), '')

offset = 0
offsets, zones = [], list(primary)
for line in CSV.read_bytes().splitlines(keepends=True):
    zone, _ = next(csv.reader([line.decode()]))
    if zone not in primary:
        offsets.append(offset)
        zones.append(zone)
    offset += len(line)
assert len(zones) == 462 and offset < 65536
country_names = [''] + sorted(set(country(zone) for zone in zones) - {''})
country_ids = [country_names.index(country(zone)) for zone in zones]
assert len(country_names) < 256
lines = ['/* Generated by tools/generate_timezone_index.py; do not reorder zones.',
         ' * CSV SHA256: ' + hashlib.sha256(CSV.read_bytes()).hexdigest(),
         ' * Country metadata: IANA 2026b, public domain; POSIX rules unchanged. */',
         'static const uint16_t s_catalog_offsets[] = {']
for start in range(0, len(offsets), 12):
    lines.append('    ' + ', '.join(map(str, offsets[start:start+12])) + ',')
lines += ['};', 'static const char *const s_country_names[] = {']
lines += ['    ' + json.dumps(name, ensure_ascii=False) + ',' for name in country_names]
lines += ['};', 'static const uint8_t s_country_ids[TIMEZONE_CATALOG_COUNT] = {']
for start in range(0, len(country_ids), 16):
    lines.append('    ' + ', '.join(map(str, country_ids[start:start+16])) + ',')
lines += ['};', '']
result = '\n'.join(lines)
if '--check' in sys.argv:
    assert OUTPUT.read_text(encoding='utf-8') == result, 'Regenerate timezone index'
else:
    OUTPUT.write_text(result, encoding='utf-8', newline='\n')
print(f'Timezone index: {len(zones)} stable entries, {sum(bool(country(z)) for z in zones)} country mappings')
